### PR TITLE
Feature/testing with rspec

### PR DESCRIPTION
**Pull request by ClaudiaRojasSoto**
# Description:
This PR aims to merge the `tetsing-with-rspec feature` into the `develop` branch. In this feature, unit tests have been added to each class in the project, in accordance with the specified requirements.
(Please read the bottom lines with Marco Lizza permission)

## General Requirements:
- [x] No linter errors in the codebase.
- [x] Follow the correct Gitflow.
- [x] Document all changes and logic in a professional manner.

## Ruby Requirements:
- [x] The codebase follows the list of best practices for Ruby as specified.

## Project Specific Requirements:
- [x] Add unit tests for the following classes:

- `Book`
- `Person`
- `Student`
- `Teacher`
- `Classroom`
- `Rental`
- All classes related to the implementation of the `Decorator` design pattern

### Changes:
**File: book_spec.rb**
- [x] Add unit tests for all methods in the Book class.
**File: person_spec.rb**
- [x] Add unit tests for all methods in the Person class.
**File: student_spec.rb**
- [x] Add unit tests for all methods in the Student class.
**File: teacher_spec.rb**
- [x] Add unit tests for all methods in the Teacher class.
**File: classroom_spec.rb**
- [x] Add unit tests for all methods in the Classroom class.
**File: rental_spec.rb**
- [x] Add unit tests for all methods in the Rental class.
**File: decorators_spec.rb**
- [x] Add unit tests for all methods in all the classes related to the decorator pattern.

### How to Test:
To test the changes, you can add the Rspec gem and run the `bundle install` command on your terminal after running the following command:

 - `rspec`

This should run all the unit tests and they should all pass.

> I have been given permission by the Student Success team to work solo this week. If you have any questions please reach out to `Marco Lizza` via the Code Reviewers Slack workspace.

Thank you for taking the time to review this PR. Your feedback is greatly appreciated.
Greetings,
@ClaudiaRojasSoto

### CODE REVIEW

**Comment by topeogunleye** [comment]
Hi @ClaudiaRojasSoto, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a pair programming project with no contributions from your partner.  Kindly report any issue you had with your partner to the `student success` team and they'll permit you to work solo or look for a suitable partner. Attach a screenshot of the message you received from `student success` stating that you can do the project alone in the pull request description and resubmit this PR👍

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Comment by ClaudiaRojasSoto** [comment]
@topeogunleye I added some lines to my pull request that Marco Lizza said:
Captura de pantalla 2023-09-06 a la(s) 16 34 14
Can you give some feedback about this to talk with Macro Lizza instead?

**Comment by ClaudiaRojasSoto** [comment]
Captura de pantalla 2023-09-06 a la(s) 16 43 57

**Review by ichala — APPROVED** [review]
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966

# To Highlight 💪🏻

- All test files are placed in a different directory ( /spec) ✔️ 
- Created one file per class✔️
- there is an 'it' block for each class method✔️
- tests are green ✔️


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ClaudiaRojasSoto** [comment]
Thank you so much @ichala.

**Comment by topeogunleye** [comment]
> @topeogunleye I added some lines to my pull request that Marco Lizza said: Captura de pantalla 2023-09-06 a la(s) 16 34 14 Can you give some feedback about this to talk with Macro Lizza instead?

Sorry, I missed the last lines. Great job adding the screenshot

**Pull request merged**
